import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";
import WhatsAppWidget from "@/components/shared/whatsapp-widget";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col min-h-screen bg-red-500">
          <Header />
          <main className="flex-grow">
            {children}
          </main>
          <Footer />

         {/* WhatsApp Widget */}
        <WhatsAppWidget 
          phoneNumber="+15551234567" 
          welcomeMessage="👋 Hello! How can we help you with your environmental testing needs today?" 
          companyName="Evergreen Enviro Consultancy and Laboratories"
          autoOpen={false}
        />
    </div>
      </body>
    </html>
  );
}
